spring:
  application:
    name: study-server
  main:
    allow-circular-references: true

  cloud:
    function:
      definition: consumeSaResult;consumeSaStopped;consumeSaFailed;consumeDsResult;consumeDsStopped;consumeDsFailed;consumeBuildResult;consumeBuildStopped;consumeBuildFailed;consumeCaseImportSucceeded;consumeCaseImportFailed;consumeSensitivityAnalysisResult;consumeSensitivityAnalysisStopped;consumeSensitivityAnalysisFailed;consumeShortCircuitAnalysisResult;consumeShortCircuitAnalysisStopped;consumeShortCircuitAnalysisFailed;consumeVoltageInitResult;consumeVoltageInitStopped;consumeVoltageInitFailed;consumeLoadFlowResult;consumeLoadFlowStopped;consumeLoadFlowFailed;consumeSensitivityAnalysisNonEvacuatedEnergyResult;consumeSensitivityAnalysisNonEvacuatedEnergyStopped;consumeSensitivityAnalysisNonEvacuatedEnergyFailed
    stream:
      bindings:
        publishStudyUpdate-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}study.update
        publishElementUpdate-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}element.update
        consumeSaResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.result
          group: studySaResultGroup
        consumeSaStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.stopped
          group: studySaStoppedGroup
        consumeSaFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.failed
          group: studySaFailedGroup
        consumeDsResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.result
          group: studyDsResultGroup
        consumeDsStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.stopped
          group: studyDsStoppedGroup
        consumeDsFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.failed
          group: studyDsFailedGroup
        consumeBuildResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.result
          group: studyBuildResultGroup
        consumeBuildStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.stopped
          group: studyBuildStoppedGroup
        consumeBuildFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.failed
          group: studyBuildFailedGroup
        consumeLoadFlowResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.result
          group: studyLoadFlowResultGroup
        consumeLoadFlowStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.stopped
          group: studyLoadFlowStoppedGroup
        consumeLoadFlowFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.failed
          group: studyLoadFlowFailedGroup
        consumeSensitivityAnalysisResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.result
          group: studySensitivityAnalysisResultGroup
        consumeSensitivityAnalysisStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.stopped
          group: studySensitivityAnalysisStoppedGroup
        consumeSensitivityAnalysisFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.failed
          group: studySensitivityAnalysisFailedGroup
        consumeSensitivityAnalysisNonEvacuatedEnergyResult-in-0:
           destination: ${powsybl-ws.rabbitmq.destination.prefix:}nonEvacuatedEnergy.result
           group: studySensitivityAnalysisNonEvacuatedEnergyResultGroup
        consumeSensitivityAnalysisNonEvacuatedEnergyStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}nonEvacuatedEnergy.stopped
          group: studySensitivityAnalysisNonEvacuatedEnergyStoppedGroup
        consumeSensitivityAnalysisNonEvacuatedEnergyFailed-in-0:
           destination: ${powsybl-ws.rabbitmq.destination.prefix:}nonEvacuatedEnergy.failed
           group: studySensitivityAnalysisNonEvacuatedEnergyFailedGroup
        consumeShortCircuitAnalysisResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}shortcircuitanalysis.result
          group: studyShortCircuitAnalysisResultGroup
        consumeShortCircuitAnalysisStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}shortcircuitanalysis.stopped
          group: studyShortCircuitAnalysisStoppedGroup
        consumeShortCircuitAnalysisFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}shortcircuitanalysis.failed
          group: studyShortCircuitAnalysisFailedGroup
        consumeVoltageInitResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}voltageinit.result
          group: studyVoltageInitResultGroup
        consumeVoltageInitStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}voltageinit.stopped
          group: studyVoltageInitStoppedGroup
        consumeVoltageInitFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}voltageinit.failed
          group: studyVoltageInitFailedGroup
        consumeCaseImportSucceeded-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.succeeded
          group: studyCaseImportSucceededGroup
        consumeCaseImportFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.failed
          group: studyCaseImportFailedGroup
      output-bindings: publishStudyUpdate-out-0;publishElementUpdate-out-0

powsybl:
  services:
    network-store-server:
      preloading-strategy: COLLECTION

powsybl-ws:
  database:
    name: study


# default values for loadflow providers "Hades2" or "OpenLoadFlow"
loadflow:
  default-provider: OpenLoadFlow

security-analysis:
  default-provider: OpenLoadFlow

sensitivity-analysis:
  default-provider: OpenLoadFlow

non-evacuated-energy:
  default-provider: OpenLoadFlow

dynamic-simulation:
  default-provider: DynaWaltz

server:
  max-http-header-size: 64000

gridsuite:
  services:
    -
      name: geo-data-server
      base-uri: http://geo-data-server/
    -
      name: network-map-server
      base-uri: http://network-map-server/
    -
      name: network-modification-server
      base-uri: http://network-modification-server/
    -
      name: loadflow-server
      base-uri: http://loadflow-server/
    -
      name: actions-server
      base-uri: http://actions-server/
    -
      name: security-analysis-server
      base-uri: http://security-analysis-server/
    -
      name: report-server
      base-uri: http://report-server/
    -
      name: sensitivity-analysis-server
      base-uri: http://sensitivity-analysis-server/
    -
      name: shortcircuit-server
      base-uri: http://shortcircuit-server/
    -
      name: dynamic-simulation-server
      base-uri: http://dynamic-simulation-server/
    -
      name: timeseries-server
      base-uri: http://timeseries-server/
    -
      name: dynamic-mapping-server
      base-uri: http://dynamic-mapping-server/
    -
      name: voltage-init-server
      base-uri: http://voltage-init-server/
