spring:
  application:
    name: study-server
  main:
    allow-circular-references: true
  cloud:
    function:
      definition: "consumeSaResult;consumeSaStopped;consumeSaFailed;consumeSaCancelFailed;\
      consumeDsDebug;consumeDsResult;consumeDsStopped;consumeDsFailed;consumeDsCancelFailed;\
      consumeDsaDebug;consumeDsaResult;consumeDsaStopped;consumeDsaFailed;consumeDsaCancelFailed;\
      consumeBuildResult;consumeBuildStopped;consumeBuildFailed;\
      consumeCaseImportSucceeded;consumeCaseImportFailed;\
      consumeSensitivityAnalysisResult;consumeSensitivityAnalysisStopped;consumeSensitivityAnalysisFailed;consumeSensitivityAnalysisCancelFailed;\
      consumeShortCircuitAnalysisDebug;consumeShortCircuitAnalysisResult;consumeShortCircuitAnalysisStopped;consumeShortCircuitAnalysisFailed;consumeShortCircuitAnalysisCancelFailed;\
      consumeVoltageInitDebug;consumeVoltageInitResult;consumeVoltageInitStopped;consumeVoltageInitFailed;consumeVoltageInitCancelFailed;\
      consumeLoadFlowResult;consumeLoadFlowStopped;consumeLoadFlowFailed;consumeLoadFlowCancelFailed;\
      consumeStateEstimationResult;consumeStateEstimationStopped;consumeStateEstimationFailed;\consumeNetworkExportFinished"
    stream:
      bindings:
        publishStudyUpdate-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}study.update
        publishElementUpdate-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}element.update
        consumeSaResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.result
          group: studySaResultGroup
        consumeSaStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.stopped
          group: studySaStoppedGroup
        consumeSaCancelFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.cancelfailed
          group: studySaCancelFailedGroup
        consumeSaFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.run.dlx
          group: dlq
        consumeDsDebug-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.debug
          group: studyDsDebugGroup
        consumeDsResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.result
          group: studyDsResultGroup
        consumeDsStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.stopped
          group: studyDsStoppedGroup
        consumeDsCancelFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.cancelfailed
          group: studyDsCancelFailedGroup
        consumeDsFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.run.dlx
          group: dlq
        consumeDsaDebug-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.debug
          group: studyDsaDebugGroup
        consumeDsaResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.result
          group: studyDsaResultGroup
        consumeDsaStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.stopped
          group: studyDsaStoppedGroup
        consumeDsaCancelFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.cancelfailed
          group: studyDsaCancelFailedGroup
        consumeDsaFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}dsa.run.dlx
          group: dlq
        consumeBuildResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.result
          group: studyBuildResultGroup
        consumeBuildStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.stopped
          group: studyBuildStoppedGroup
        consumeBuildFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.run.dlx
          group: dlq
        consumeLoadFlowResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.result
          group: studyLoadFlowResultGroup
        consumeLoadFlowStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.stopped
          group: studyLoadFlowStoppedGroup
        consumeLoadFlowFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.run.dlx
          group: dlq
        consumeLoadFlowCancelFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.cancelfailed
          group: studyLoadFlowCancelFailedGroup
        consumeSensitivityAnalysisResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.result
          group: studySensitivityAnalysisResultGroup
        consumeSensitivityAnalysisStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.stopped
          group: studySensitivityAnalysisStoppedGroup
        consumeSensitivityAnalysisFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.run.dlx
          group: dlq
        consumeSensitivityAnalysisCancelFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.cancelfailed
          group: studySensitivityAnalysisCancelFailedGroup
        consumeShortCircuitAnalysisDebug-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}shortcircuitanalysis.debug
          group: studyShortCircuitAnalysisDebugGroup
        consumeShortCircuitAnalysisResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}shortcircuitanalysis.result
          group: studyShortCircuitAnalysisResultGroup
        consumeShortCircuitAnalysisStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}shortcircuitanalysis.stopped
          group: studyShortCircuitAnalysisStoppedGroup
        consumeShortCircuitAnalysisFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}shortcircuitanalysis.run.dlx
          group: dlq
        consumeShortCircuitAnalysisCancelFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}shortcircuitanalysis.cancelfailed
          group: studyShortCircuitAnalysisCancelFailedGroup
        consumeVoltageInitDebug-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}voltageinit.debug
          group: studyVoltageInitDebugGroup
        consumeVoltageInitResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}voltageinit.result
          group: studyVoltageInitResultGroup
        consumeVoltageInitStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}voltageinit.stopped
          group: studyVoltageInitStoppedGroup
        consumeVoltageInitFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}voltageinit.run.dlx
          group: dlq
        consumeVoltageInitCancelFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}voltageinit.cancelfailed
          group: studyVoltageInitCancelFailedGroup
        consumeStateEstimationResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}stateestimation.result
          group: studyStateEstimationResultGroup
        consumeStateEstimationStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}stateestimation.stopped
          group: studyStateEstimationStoppedGroup
        consumeStateEstimationFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}stateestimation.run.dlx
          group: dlq
        consumeCaseImportSucceeded-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.succeeded
          group: studyCaseImportSucceededGroup
        consumeCaseImportFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.start.dlx
          group: dlq
        consumeNetworkExportFinished-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}network.export.finished
          group: dlq
      output-bindings: publishStudyUpdate-out-0;publishElementUpdate-out-0

powsybl:
  services:
    network-store-server:
      preloading-strategy: COLLECTION

powsybl-ws:
  database:
    name: study

dynamic-simulation:
  default-provider: Dynawo

server:
  max-http-header-size: 64000

gridsuite:
  services:
    -
      name: geo-data-server
      base-uri: http://geo-data-server/
    -
      name: network-map-server
      base-uri: http://network-map-server/
    -
      name: network-modification-server
      base-uri: http://network-modification-server/
    -
      name: loadflow-server
      base-uri: http://loadflow-server/
    -
      name: actions-server
      base-uri: http://actions-server/
    -
      name: security-analysis-server
      base-uri: http://security-analysis-server/
    -
      name: report-server
      base-uri: http://report-server/
    -
      name: sensitivity-analysis-server
      base-uri: http://sensitivity-analysis-server/
    -
      name: shortcircuit-server
      base-uri: http://shortcircuit-server/
    -
      name: dynamic-simulation-server
      base-uri: http://dynamic-simulation-server/
    -
      name: dynamic-security-analysis-server
      base-uri: http://dynamic-security-analysis-server/
    -
      name: timeseries-server
      base-uri: http://timeseries-server/
    -
      name: dynamic-mapping-server
      base-uri: http://dynamic-mapping-server/
    -
      name: voltage-init-server
      base-uri: http://voltage-init-server/
    -
      name: filter-server
      base-uri: http://filter-server/
    -
      name: state-estimation-server
      base-uri: http://state-estimation-server/
    -
      name: study-config-server
      base-uri: http://study-config-server/
    -
      name: directory-server
      base-uri: http://directory-server/

study:
  max-root-network-by-study: 4
