spring:
  application:
    name: study-server
  main:
    allow-circular-references: true

  cloud:
    function:
      definition: consumeSaResult;consumeSaStopped;consumeSaFailed;consumeBuildResult;consumeBuildStopped;consumeBuildFailed;consumeCaseImportSucceeded;consumeCaseImportFailed;consumeSensitivityAnalysisResult;consumeSensitivityAnalysisStopped;consumeSensitivityAnalysisFailed
    stream:
      bindings:
        publishStudyUpdate-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}study.update
        consumeSaResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.result
          group: studySaResultGroup
        consumeSaStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.stopped
          group: studySaStoppedGroup
        consumeSaFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.failed
          group: studySaFailedGroup
        consumeBuildResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.result
          group: studyBuildResultGroup
        consumeBuildStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.stopped
          group: studyBuildStoppedGroup
        consumeBuildFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.failed
          group: studyBuildFailedGroup
        consumeSensitivityAnalysisResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.result
          group: studySensitivityAnalysisResultGroup
        consumeSensitivityAnalysisStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.stopped
          group: studySensitivityAnalysisStoppedGroup
        consumeSensitivityAnalysisFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sensitivityanalysis.failed
          group: studySensitivityAnalysisFailedGroup
        consumeCaseImportSucceeded-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.succeeded
          group: studyCaseImportSucceededGroup
        consumeCaseImportFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.failed
          group: studyCaseImportFailedGroup
      source: publishStudyUpdate

network-store-server:
  preloading-strategy: COLLECTION

powsybl-ws:
  database:
    name: study


# default values for loadflow providers "Hades2" or "OpenLoadFlow"
loadflow:
  default-provider: OpenLoadFlow

server:
  max-http-header-size: 64000