spring:
  application:
    name: study-server
  main:
    allow-circular-references: true

  cloud:
    function:
      definition: consumeSaResult;consumeSaStopped;consumeSaFailed;consumeBuildResult;consumeBuildStopped;consumeBuildFailed;consumeCaseImportSucceeded;consumeCaseImportFailed
    stream:
      bindings:
        publishStudyUpdate-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}study.update
        consumeSaResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.result
        consumeSaStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.stopped
        consumeSaFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.failed
        consumeBuildResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.result
        consumeBuildStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.stopped
        consumeBuildFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.failed
        consumeCaseImportSucceeded-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.succeeded
        consumeCaseImportFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import.failed
      output-bindings: publishStudyUpdate

network-store-server:
  preloading-strategy: COLLECTION

dbName: study


# default values for loadflow providers "Hades2" or "OpenLoadFlow"
loadflow:
  default-provider: OpenLoadFlow

server:
  max-http-header-size: 64000