spring:
  application:
    name: study-server
  main:
    allow-circular-references: true

  cloud:
    function:
      definition: consumeStudyCreate;consumeSaResult;consumeSaStopped;consumeSaFailed;consumeBuildResult;consumeBuildStopped;consumeBuildFailed
    stream:
      bindings:
        publishStudyUpdate-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}study.update
        publishStudyCreate-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}study.create
        consumeStudyCreate-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}study.create
        consumeSaResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.result
        consumeSaStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.stopped
        consumeSaFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.failed
        consumeBuildResult-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.result
        consumeBuildStopped-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.stopped
        consumeBuildFailed-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}build.failed
      source: publishStudyUpdate;publishStudyCreate

network-store-server:
  preloading-strategy: COLLECTION

dbName: study


# default values for loadflow providers "Hades2" or "OpenLoadFlow"
loadflow:
  default-provider: OpenLoadFlow
