/**
 * Copyright (c) 2019, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package org.gridsuite.study.server;

import java.util.Objects;

/**
 * @author Abdelsalem Hedhili <abdelsalem.hedhili at rte-france.com>
 */
public class StudyException extends RuntimeException {

    public enum Type {
        STUDY_ALREADY_EXISTS,
        ELEMENT_NOT_FOUND,
        STUDY_NOT_FOUND,
        DIAGRAM_GRID_LAYOUT_NOT_FOUND,
        CASE_NOT_FOUND,
        LOADFLOW_NOT_RUNNABLE,
        LOADFLOW_RUNNING,
        LOADFLOW_ERROR,
        SECURITY_ANALYSIS_RUNNING,
        SECURITY_ANALYSIS_NOT_FOUND,
        SENSITIVITY_ANALYSIS_RUNNING,
        SENSITIVITY_ANALYSIS_NOT_FOUND,
        SENSITIVITY_ANALYSIS_ERROR,
        SHORT_CIRCUIT_ANALYSIS_NOT_FOUND,
        SHORT_CIRCUIT_ANALYSIS_ERROR,
        LOADFLOW_NOT_FOUND,
        SHORT_CIRCUIT_ANALYSIS_RUNNING,
        VOLTAGE_INIT_NOT_FOUND,
        VOLTAGE_INIT_RUNNING,
        DYNAMIC_SIMULATION_RUNNING,
        DYNAMIC_SIMULATION_NOT_FOUND,
        DYNAMIC_MAPPING_NOT_FOUND,
        DYNAMIC_SECURITY_ANALYSIS_RUNNING,
        DYNAMIC_SECURITY_ANALYSIS_NOT_FOUND,
        DYNAMIC_SECURITY_ANALYSIS_ERROR,
        NOT_ALLOWED,
        STUDY_CREATION_FAILED,
        CANT_DELETE_ROOT_NODE,
        DELETE_EQUIPMENT_FAILED,
        DELETE_NODE_FAILED,
        DELETE_STUDY_FAILED,
        DELETE_ROOT_NETWORK_FAILED,
        CREATE_NETWORK_MODIFICATION_FAILED,
        UPDATE_NETWORK_MODIFICATION_FAILED,
        DELETE_NETWORK_MODIFICATION_FAILED,
        MOVE_NETWORK_MODIFICATION_FORBIDDEN,
        UNKNOWN_EQUIPMENT_TYPE,
        BAD_NODE_TYPE,
        NETWORK_NOT_FOUND,
        EQUIPMENT_NOT_FOUND,
        NETWORK_INDEXATION_FAILED,
        NODE_NOT_FOUND,
        NODE_NOT_BUILT,
        SVG_NOT_FOUND,
        NODE_NAME_ALREADY_EXIST,
        NODE_BUILD_ERROR,
        INVALIDATE_BUILD_FAILED,
        UNKNOWN_NOTIFICATION_TYPE,
        BAD_MODIFICATION_TYPE,
        GET_MODIFICATIONS_FAILED,
        GET_MODIFICATIONS_COUNT_FAILED,
        GET_NETWORK_ELEMENT_FAILED,
        GET_NETWORK_COUNTRY_FAILED,
        GET_NETWORK_NOMINAL_VOLTAGES_FAILED,
        BAD_JSON_FORMAT,
        UNKNOWN_ACTION_TYPE,
        BAD_PARAMETER,
        MISSING_PARAMETER,
        LOAD_SCALING_FAILED,
        DELETE_VOLTAGE_LEVEL_ON_LINE,
        DELETE_ATTACHING_LINE,
        GENERATOR_SCALING_FAILED,
        URI_SYNTAX,
        TIME_SERIES_BAD_TYPE,
        TIMELINE_BAD_TYPE,
        FILTERS_NOT_FOUND,
        NO_VOLTAGE_INIT_RESULTS_FOR_NODE,
        NO_VOLTAGE_INIT_MODIFICATIONS_GROUP_FOR_NODE,
        VOLTAGE_INIT_PARAMETERS_NOT_FOUND,
        CREATE_VOLTAGE_INIT_PARAMETERS_FAILED,
        UPDATE_VOLTAGE_INIT_PARAMETERS_FAILED,
        CREATE_SECURITY_ANALYSIS_PARAMETERS_FAILED,
        UPDATE_SECURITY_ANALYSIS_PARAMETERS_FAILED,
        GET_SECURITY_ANALYSIS_PARAMETERS_FAILED,
        SECURITY_ANALYSIS_PARAMETERS_NOT_FOUND,
        GET_SECURITY_ANALYSIS_DEFAULT_PROVIDER_FAILED,
        UPDATE_SECURITY_ANALYSIS_PROVIDER_FAILED,
        CREATE_LOADFLOW_PARAMETERS_FAILED,
        UPDATE_LOADFLOW_PARAMETERS_FAILED,
        GET_LOADFLOW_PARAMETERS_FAILED,
        DELETE_LOADFLOW_PARAMETERS_FAILED,
        LOADFLOW_PARAMETERS_NOT_FOUND,
        GET_LOADFLOW_DEFAULT_PROVIDER_FAILED,
        UPDATE_LOADFLOW_PROVIDER_FAILED,
        UPDATE_SHORTCIRCUIT_PARAMETERS_FAILED,
        CREATE_SHORTCIRCUIT_PARAMETERS_FAILED,
        GET_SHORTCIRCUIT_PARAMETERS_FAILED,
        SENSITIVITY_ANALYSIS_PARAMETERS_NOT_FOUND,
        GET_SENSITIVITY_ANALYSIS_PARAMETERS_FAILED,
        CREATE_SENSITIVITY_ANALYSIS_PARAMETERS_FAILED,
        UPDATE_SENSITIVITY_ANALYSIS_PARAMETERS_FAILED,
        DELETE_SENSITIVITY_ANALYSIS_PARAMETERS_FAILED,
        GET_SENSITIVITY_ANALYSIS_DEFAULT_PROVIDER_FAILED,
        UPDATE_SENSITIVITY_ANALYSIS_PROVIDER_FAILED,
        GET_DYNAMIC_SECURITY_ANALYSIS_PARAMETERS_FAILED,
        CREATE_DYNAMIC_SECURITY_ANALYSIS_PARAMETERS_FAILED,
        CREATE_DYNAMIC_SECURITY_ANALYSIS_DEFAULT_PARAMETERS_FAILED,
        RUN_DYNAMIC_SECURITY_ANALYSIS_FAILED,
        RUN_DYNAMIC_SIMULATION_FAILED,
        INVALIDATE_DYNAMIC_SECURITY_ANALYSIS_FAILED,
        DUPLICATE_DYNAMIC_SECURITY_ANALYSIS_PARAMETERS_FAILED,
        UPDATE_DYNAMIC_SECURITY_ANALYSIS_PARAMETERS_FAILED,
        DYNAMIC_SECURITY_ANALYSIS_PARAMETERS_NOT_FOUND,
        DYNAMIC_SECURITY_ANALYSIS_PROVIDER_NOT_FOUND,
        GET_DYNAMIC_SECURITY_ANALYSIS_PROVIDER_FAILED,
        DYNAMIC_SECURITY_ANALYSIS_DEFAULT_PROVIDER_NOT_FOUND,
        GET_DYNAMIC_SECURITY_ANALYSIS_DEFAULT_PROVIDER_FAILED,
        UPDATE_DYNAMIC_SECURITY_ANALYSIS_PROVIDER_FAILED,
        DELETE_COMPUTATION_RESULTS_FAILED,
        STUDY_INDEXATION_FAILED,
        STUDY_CHECK_INDEXATION_FAILED,
        NOT_IMPLEMENTED,
        EVALUATE_FILTER_FAILED,
        GET_USER_PROFILE_FAILED,
        STATE_ESTIMATION_RUNNING,
        STATE_ESTIMATION_NOT_FOUND,
        STATE_ESTIMATION_ERROR,
        CREATE_STATE_ESTIMATION_PARAMETERS_FAILED,
        UPDATE_STATE_ESTIMATION_PARAMETERS_FAILED,
        DELETE_STATE_ESTIMATION_PARAMETERS_FAILED,
        GET_STATE_ESTIMATION_PARAMETERS_FAILED,
        STATE_ESTIMATION_PARAMETERS_NOT_FOUND,
        MAX_NODE_BUILDS_EXCEEDED,
        CREATE_NETWORK_VISUALIZATION_PARAMETERS_FAILED,
        UPDATE_NETWORK_VISUALIZATION_PARAMETERS_FAILED,
        NETWORK_VISUALIZATION_PARAMETERS_NOT_FOUND,
        GET_NETWORK_VISUALIZATION_PARAMETERS_FAILED,
        ROOT_NETWORK_NOT_FOUND,
        ROOT_NETWORK_DELETE_FORBIDDEN,
        ROOT_NETWORK_CREATION_FAILED,
        ROOT_NETWORK_MODIFICATION_FAILED,
        MAXIMUM_ROOT_NETWORK_BY_STUDY_REACHED,
        MAXIMUM_TAG_LENGTH_EXCEEDED,
        DUPLICATE_SPREADSHEET_CONFIG_COLLECTION_FAILED,
        SPREADSHEET_CONFIG_COLLECTION_NOT_FOUND,
        GET_SPREADSHEET_CONFIG_COLLECTION_FAILED,
        CREATE_SPREADSHEET_CONFIG_COLLECTION_FAILED,
        UPDATE_SPREADSHEET_CONFIG_COLLECTION_FAILED,
        UPDATE_SPREADSHEET_CONFIG_FAILED,
        NETWORK_EXPORT_FAILED,
        GET_LOADFLOW_PROVIDER_FAILED,
        CREATE_DIAGRAM_GRID_LAYOUT_FAILED,
        DUPLICATE_DIAGRAM_GRID_LAYOUT_FAILED,
        TOO_MANY_NAD_CONFIGS,
        TOO_MANY_MAP_CARDS
    }

    private final Type type;

    public StudyException(Type type) {
        super(Objects.requireNonNull(type.name()));
        this.type = type;
    }

    public StudyException(Type type, String message) {
        super(message);
        this.type = type;
    }

    Type getType() {
        return type;
    }
}
