/**
 * Copyright (c) 2025, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package org.gridsuite.study.server;

import com.powsybl.ws.commons.error.BusinessErrorCode;

/**
 * @author Joris Mancini <joris.mancini_externe at rte-france.com>
 */
public enum StudyBusinessErrorCode implements BusinessErrorCode {
    STUDY_ALREADY_EXISTS("study.alreadyExists"),
    ELEMENT_NOT_FOUND("study.elementNotFound"),
    STUDY_NOT_FOUND("study.studyNotFound"),
    DIAGRAM_GRID_LAYOUT_NOT_FOUND("study.diagramGridLayoutNotFound"),
    CASE_NOT_FOUND("study.caseNotFound"),
    LOADFLOW_NOT_RUNNABLE("study.loadflowNotRunning"),
    LOADFLOW_RUNNING("study.loadflowRunning"),
    LOADFLOW_ERROR("study.loadflowError"),
    SECURITY_ANALYSIS_RUNNING("study.securityAnalysisRunning"),
    SECURITY_ANALYSIS_NOT_FOUND("study.securityAnalysisNotFound"),
    SENSITIVITY_ANALYSIS_RUNNING("study.sensitivityAnalysisRunning"),
    SENSITIVITY_ANALYSIS_NOT_FOUND("study.sensitivityAnalysisNotFound"),
    SENSITIVITY_ANALYSIS_ERROR("study.sensitivityAnalysisError"),
    SHORT_CIRCUIT_ANALYSIS_NOT_FOUND("study.shortCircuitAnalysisNotFound"),
    SHORT_CIRCUIT_ANALYSIS_ERROR("study.shortCircuitAnalysisError"),
    LOADFLOW_NOT_FOUND("study.loadflowNotFound"),
    SHORT_CIRCUIT_ANALYSIS_RUNNING("study.shortCircuitAnalysisRunning"),
    VOLTAGE_INIT_NOT_FOUND("study.voltageInitNotFound"),
    VOLTAGE_INIT_RUNNING("study.voltageInitRunning"),
    DYNAMIC_SIMULATION_RUNNING("study.dynamicSimulationRunning"),
    DYNAMIC_SIMULATION_NOT_FOUND("study.dynamicSimulationNotFound"),
    DYNAMIC_MAPPING_NOT_FOUND("study.dynamicMappingNotFound"),
    DYNAMIC_SECURITY_ANALYSIS_RUNNING("study.dynamicSecurityAnalysisRunning"),
    DYNAMIC_SECURITY_ANALYSIS_NOT_FOUND("study.dynamicSecurityAnalysisNotFound"),
    DYNAMIC_SECURITY_ANALYSIS_ERROR("study.dynamicSecurityAnalysisError"),
    NOT_ALLOWED("study.notAllowed"),
    STUDY_CREATION_FAILED("study.studyCreationFailed"),
    CANT_DELETE_ROOT_NODE("study.cantDeleteRootNode"),
    DELETE_EQUIPMENT_FAILED("study.deleteEquipmentFailed"),
    DELETE_NODE_FAILED("study.deleteNodeFailed"),
    DELETE_STUDY_FAILED("study.deleteStudyFailed"),
    DELETE_ROOT_NETWORK_FAILED("study.deleteRootNetworkFailed"),
    CREATE_NETWORK_MODIFICATION_FAILED("study.createNetworkModificationFailed"),
    UPDATE_NETWORK_MODIFICATION_FAILED("study.updateNetworkModificationFailed"),
    DELETE_NETWORK_MODIFICATION_FAILED("study.deleteNetworkModificationFailed"),
    MOVE_NETWORK_MODIFICATION_FORBIDDEN("study.moveNetworkModificationForbidden"),
    UNKNOWN_EQUIPMENT_TYPE("study.unknownEquipmentType"),
    BAD_NODE_TYPE("study.badNodeType"),
    NETWORK_NOT_FOUND("study.networkNotFound"),
    EQUIPMENT_NOT_FOUND("study.equipmentNotFound"),
    NETWORK_INDEXATION_FAILED("study.networkIndexationFailed"),
    NODE_NOT_FOUND("study.nodeNotFound"),
    NODE_NOT_BUILT("study.nodeNotBuilt"),
    SVG_NOT_FOUND("study.svgNotFound"),
    NODE_NAME_ALREADY_EXIST("study.nodeNameAlreadyExist"),
    NODE_BUILD_ERROR("study.nodeBuildError"),
    INVALIDATE_BUILD_FAILED("study.invalidateBuildFailed"),
    UNKNOWN_NOTIFICATION_TYPE("study.unknownNotificationType"),
    BAD_MODIFICATION_TYPE("study.badModificationType"),
    GET_MODIFICATIONS_FAILED("study.getModificationsFailed"),
    GET_MODIFICATIONS_COUNT_FAILED("study.getModificationsCountFailed"),
    GET_NETWORK_ELEMENT_FAILED("study.getNetworkElementFailed"),
    GET_NETWORK_COUNTRY_FAILED("study.getNetworkCountryFailed"),
    GET_NETWORK_NOMINAL_VOLTAGES_FAILED("study.getNetworkNominalVoltagesFailed"),
    BAD_JSON_FORMAT("study.badJsonFormat"),
    UNKNOWN_ACTION_TYPE("study.unknownActionType"),
    BAD_PARAMETER("study.badParameter"),
    MISSING_PARAMETER("study.missingParameter"),
    LOAD_SCALING_FAILED("study.loadScalingFailed"),
    DELETE_VOLTAGE_LEVEL_ON_LINE("study.deleteVoltageLevelOnLine"),
    DELETE_ATTACHING_LINE("study.deleteAttachingLine"),
    GENERATOR_SCALING_FAILED("study.generatorScalingFailed"),
    URI_SYNTAX("study.uriSyntax"),
    TIME_SERIES_BAD_TYPE("study.timeSeriesBadType"),
    TIMELINE_BAD_TYPE("study.timelineBadType"),
    FILTERS_NOT_FOUND("study.filtersNotFound"),
    NO_VOLTAGE_INIT_RESULTS_FOR_NODE("study.noVoltageInitResultsForNode"),
    NO_VOLTAGE_INIT_MODIFICATIONS_GROUP_FOR_NODE("study.noVoltageInitModificationsGroupForNode"),
    VOLTAGE_INIT_PARAMETERS_NOT_FOUND("study.voltageInitParametersNotFound"),
    CREATE_VOLTAGE_INIT_PARAMETERS_FAILED("study.createVoltageInitParametersFailed"),
    UPDATE_VOLTAGE_INIT_PARAMETERS_FAILED("study.updateVoltageInitParametersFailed"),
    CREATE_SECURITY_ANALYSIS_PARAMETERS_FAILED("study.createSecurityAnalysisParametersFailed"),
    UPDATE_SECURITY_ANALYSIS_PARAMETERS_FAILED("study.updateSecurityAnalysisParametersFailed"),
    GET_SECURITY_ANALYSIS_PARAMETERS_FAILED("study.getSecurityAnalysisParametersFailed"),
    SECURITY_ANALYSIS_PARAMETERS_NOT_FOUND("study.securityAnalysisParametersNotFound"),
    GET_SECURITY_ANALYSIS_DEFAULT_PROVIDER_FAILED("study.getSecurityAnalysisDefaultProviderFailed"),
    UPDATE_SECURITY_ANALYSIS_PROVIDER_FAILED("study.updateSecurityAnalysisProviderFailed"),
    CREATE_LOADFLOW_PARAMETERS_FAILED("study.createLoadflowParametersFailed"),
    UPDATE_LOADFLOW_PARAMETERS_FAILED("study.updateLoadflowParametersFailed"),
    GET_LOADFLOW_PARAMETERS_FAILED("study.getLoadflowParametersFailed"),
    DELETE_LOADFLOW_PARAMETERS_FAILED("study.deleteLoadflowParametersFailed"),
    LOADFLOW_PARAMETERS_NOT_FOUND("study.loadflowParametersNotFound"),
    GET_LOADFLOW_DEFAULT_PROVIDER_FAILED("study.getLoadflowDefaultProviderFailed"),
    UPDATE_LOADFLOW_PROVIDER_FAILED("study.updateLoadflowProviderFailed"),
    UPDATE_SHORTCIRCUIT_PARAMETERS_FAILED("study.updateShortcircuitParametersFailed"),
    CREATE_SHORTCIRCUIT_PARAMETERS_FAILED("study.createShortcircuitParametersFailed"),
    GET_SHORTCIRCUIT_PARAMETERS_FAILED("study.getShortcircuitParametersFailed"),
    SENSITIVITY_ANALYSIS_PARAMETERS_NOT_FOUND("study.sensitivityAnalysisParametersNotFound"),
    GET_SENSITIVITY_ANALYSIS_PARAMETERS_FAILED("study.getSensitivityAnalysisParametersFailed"),
    CREATE_SENSITIVITY_ANALYSIS_PARAMETERS_FAILED("study.createSensitivityAnalysisParametersFailed"),
    UPDATE_SENSITIVITY_ANALYSIS_PARAMETERS_FAILED("study.updateSensitivityAnalysisParametersFailed"),
    DELETE_SENSITIVITY_ANALYSIS_PARAMETERS_FAILED("study.deleteSensitivityAnalysisParametersFailed"),
    GET_SENSITIVITY_ANALYSIS_DEFAULT_PROVIDER_FAILED("study.getSensitivityAnalysisDefaultProviderFailed"),
    UPDATE_SENSITIVITY_ANALYSIS_PROVIDER_FAILED("study.updateSensitivityAnalysisProviderFailed"),
    GET_DYNAMIC_SECURITY_ANALYSIS_PARAMETERS_FAILED("study.getDynamicSecurityAnalysisParametersFailed"),
    CREATE_DYNAMIC_SECURITY_ANALYSIS_PARAMETERS_FAILED("study.createDynamicSecurityAnalysisParametersFailed"),
    CREATE_DYNAMIC_SECURITY_ANALYSIS_DEFAULT_PARAMETERS_FAILED("study.createDynamicSecurityAnalysisDefaultParametersFailed"),
    RUN_DYNAMIC_SECURITY_ANALYSIS_FAILED("study.runDynamicSecurityAnalysisFailed"),
    RUN_DYNAMIC_SIMULATION_FAILED("study.runDynamicSimulationFailed"),
    INVALIDATE_DYNAMIC_SECURITY_ANALYSIS_FAILED("study.invalidateDynamicSecurityAnalysisFailed"),
    DUPLICATE_DYNAMIC_SECURITY_ANALYSIS_PARAMETERS_FAILED("study.duplicateDynamicSecurityAnalysisParametersFailed"),
    UPDATE_DYNAMIC_SECURITY_ANALYSIS_PARAMETERS_FAILED("study.updateDynamicSecurityAnalysisParametersFailed"),
    DYNAMIC_SECURITY_ANALYSIS_PARAMETERS_NOT_FOUND("study.dynamicSecurityAnalysisParametersNotFound"),
    DYNAMIC_SECURITY_ANALYSIS_PROVIDER_NOT_FOUND("study.dynamicSecurityAnalysisProviderNotFound"),
    GET_DYNAMIC_SECURITY_ANALYSIS_PROVIDER_FAILED("study.getDynamicSecurityAnalysisProviderFailed"),
    DYNAMIC_SECURITY_ANALYSIS_DEFAULT_PROVIDER_NOT_FOUND("study.dynamicSecurityAnalysisDefaultProviderNotFound"),
    GET_DYNAMIC_SECURITY_ANALYSIS_DEFAULT_PROVIDER_FAILED("study.getDynamicSecurityAnalysisDefaultProviderFailed"),
    UPDATE_DYNAMIC_SECURITY_ANALYSIS_PROVIDER_FAILED("study.updateDynamicSecurityAnalysisProviderFailed"),
    DELETE_COMPUTATION_RESULTS_FAILED("study.deleteComputationResultsFailed"),
    STUDY_INDEXATION_FAILED("study.studyIndexationFailed"),
    STUDY_CHECK_INDEXATION_FAILED("study.studyCheckIndexationFailed"),
    NOT_IMPLEMENTED("study.notImplemented"),
    EVALUATE_FILTER_FAILED("study.evaluateFilterFailed"),
    GET_USER_PROFILE_FAILED("study.getUserProfileFailed"),
    STATE_ESTIMATION_RUNNING("study.stateEstimationRunning"),
    STATE_ESTIMATION_NOT_FOUND("study.stateEstimationNotFound"),
    STATE_ESTIMATION_ERROR("study.stateEstimationError"),
    CREATE_STATE_ESTIMATION_PARAMETERS_FAILED("study.createStateEstimationParametersFailed"),
    UPDATE_STATE_ESTIMATION_PARAMETERS_FAILED("study.updateStateEstimationParametersFailed"),
    DELETE_STATE_ESTIMATION_PARAMETERS_FAILED("study.deleteStateEstimationParametersFailed"),
    GET_STATE_ESTIMATION_PARAMETERS_FAILED("study.getStateEstimationParametersFailed"),
    STATE_ESTIMATION_PARAMETERS_NOT_FOUND("study.stateEstimationParametersNotFound"),
    PCC_MIN_RUNNING("study.pccMinRunning"),
    PCC_MIN_NOT_FOUND("study.pccMinNotFound"),
    PCC_MIN_ERROR("study.pccMinError"),
    MAX_NODE_BUILDS_EXCEEDED("study.maxNodeBuildsExceeded"),
    CREATE_NETWORK_VISUALIZATION_PARAMETERS_FAILED("study.createNetworkVisualizationParametersFailed"),
    UPDATE_NETWORK_VISUALIZATION_PARAMETERS_FAILED("study.updateNetworkVisualizationParametersFailed"),
    NETWORK_VISUALIZATION_PARAMETERS_NOT_FOUND("study.networkVisualizationParametersNotFound"),
    GET_NETWORK_VISUALIZATION_PARAMETERS_FAILED("study.getNetworkVisualizationParametersFailed"),
    ROOT_NETWORK_NOT_FOUND("study.rootNetworkNotFound"),
    ROOT_NETWORK_DELETE_FORBIDDEN("study.rootNetworkDeleteForbidden"),
    ROOT_NETWORK_CREATION_FAILED("study.rootNetworkCreationFailed"),
    ROOT_NETWORK_MODIFICATION_FAILED("study.rootNetworkModificationFailed"),
    MAXIMUM_ROOT_NETWORK_BY_STUDY_REACHED("study.maximumRootNetworkByStudyReached"),
    MAXIMUM_TAG_LENGTH_EXCEEDED("study.maximumTagLengthExceeded"),
    DUPLICATE_SPREADSHEET_CONFIG_COLLECTION_FAILED("study.duplicateSpreadsheetConfigCollectionFailed"),
    SPREADSHEET_CONFIG_COLLECTION_NOT_FOUND("study.spreadsheetConfigCollectionNotFound"),
    GET_SPREADSHEET_CONFIG_COLLECTION_FAILED("study.getSpreadsheetConfigCollectionFailed"),
    CREATE_SPREADSHEET_CONFIG_COLLECTION_FAILED("study.createSpreadsheetConfigCollectionFailed"),
    UPDATE_SPREADSHEET_CONFIG_COLLECTION_FAILED("study.updateSpreadsheetConfigCollectionFailed"),
    UPDATE_SPREADSHEET_CONFIG_FAILED("study.updateSpreadsheetConfigFailed"),
    NETWORK_EXPORT_FAILED("study.networkExportFailed"),
    GET_LOADFLOW_PROVIDER_FAILED("study.getLoadflowProviderFailed"),
    CREATE_DIAGRAM_GRID_LAYOUT_FAILED("study.createDiagramGridLayoutFailed"),
    DUPLICATE_DIAGRAM_GRID_LAYOUT_FAILED("study.duplicateDiagramGridLayoutFailed"),
    TOO_MANY_NAD_CONFIGS("study.tooManyNadConfigs"),
    TOO_MANY_MAP_CARDS("study.tooManyMapCards");

    private final String value;

    StudyBusinessErrorCode(String value) {
        this.value = value;
    }

    @Override
    public String value() {
        return value;
    }
}
