server :
  port : 5001
  forward-headers-strategy: framework

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 103MB
  codec:
    max-in-memory-size: 100MB

  rabbitmq:
    addresses: localhost
    port: 5672

  cloud:
    function:
      definition: consumeSaResult;consumeSaStopped
    stream:
      bindings:
        publishStudyUpdate-out-0:
          destination: study.update
        consumeSaResult-in-0:
          destination: sa.result
        consumeSaStopped-in-0:
          destination: sa.stopped
      source: publishStudyUpdate
  datasource:
    url: ${dbApi}:${dbVendor}://${hostPort}/${dbName}${query}
    username: ${login}
    password: ${password}

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
        # Used when action: create is uncommented
        hbm2ddl:
          delimiter: ;
      # Uncomment action to automatically generate the database sql schema file
      javax:
       persistence:
        schema-generation:
         scripts:
          #action: create
          create-target: src/main/resources/study.sql
          create-source: metadata

backing-services:
  case:
    base-uri: http://localhost:5000
  single-line-diagram:
    base-uri: http://localhost:5005
  network-conversion:
    base-uri: http://localhost:5003
  geo-data:
    base-uri: http://localhost:8087
  network-map:
    base-uri: http://localhost:5006
  network-modification:
    base-uri: http://localhost:5007
  loadflow:
    base-uri: http://localhost:5008
  actions-server:
    base-uri: http://localhost:5022
  security-analysis-server:
    base-uri: http://localhost:5023
  directory-server:
    base-uri: http://localhost:5026
  report-server:
    base-uri: http://localhost:5028

network-store-server:
  preloading-strategy: COLLECTION
  base-uri: http://localhost:8080/

dbName: study
dbApi: jdbc
