server :
  port : 5001

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 103MB
  codec:
    max-in-memory-size: 100MB

  rabbitmq:
    addresses: localhost
    port: 5672

  cloud:
    function:
      definition: publishStudyUpdate;consumeSaResult
    stream:
      bindings:
        publishStudyUpdate-out-0:
          destination: study.update
        consumeSaResult-in-0:
          destination: sa.result

backing-services:
  case:
    base-uri: http://localhost:5000
  single-line-diagram:
    base-uri: http://localhost:5005
  network-conversion:
    base-uri: http://localhost:5003
  geo-data:
    base-uri: http://localhost:8087
  network-map:
    base-uri: http://localhost:5006
  network-modification:
    base-uri: http://localhost:5007
  loadflow:
    base-uri: http://localhost:5008
  security-analysis-server:
    base-uri: http://localhost:5023

network-store-server:
  preloading-strategy: COLLECTION
  base-uri: http://localhost:8080/

