package org.gridsuite.study.server.utils;

public enum EquipmentType {
    NETWORK,
    SUBSTATION,
    VOLTAGE_LEVEL,
    HVDC_LINE,
    BUS,
    SWITCH,
    BUSBAR_SECTION,
    LINE,
    TWO_WINDINGS_TRANSFORMER,
    THREE_WINDINGS_TRANSFORMER,
    GENERATOR,
    BATTERY,
    LOAD,
    SHUNT_COMPENSATOR,
    DANGLING_LINE,
    STATIC_VAR_COMPENSATOR,
    HVDC_CONVERTER_STATION,
    LCC_CONVERTER_STATION,
    VSC_CONVERTER_STATION;
}
