name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-backend-app-generic.yml@39565de6fd7d394ed76fa09e5197ffb1350ff1e6
    with:
      dockerImage: docker.io/gridsuite/study-server
      dockerUsername: gridsuiteci
      eventType: study_server_updated
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
