name: CI

on:
  push:
  repository_dispatch:
    types: network_store_updated

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download cassandra 4.0-alpha3
        run : cd && wget "https://downloads.apache.org/cassandra/4.0-alpha3/apache-cassandra-4.0-alpha3-bin.tar.gz"

      - name: untar cassandra
        run: cd && tar xvzf apache-cassandra-4.0-alpha3-bin.tar.gz

      - name: Change cassandra storage port
        run: >
          cd
          && cd ./apache-cassandra-4.0-alpha3/conf/
          && sed -i 's/- seeds: "127.0.0.1:7000/- seeds: "127.0.0.1:16432"' ./cassandra.yaml

      - name: Checkout network store sources
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-network-store
          ref: refs/heads/master

      - name: Build and install network store client with Maven
        run: mvn --batch-mode -Pclient -DskipTests=true --file ../powsybl-network-store/pom.xml install

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Build with Maven
        run: mvn --batch-mode -P jacoco,perform-integration-test install

      - name: Run SonarCloud analysis
        run: >
          mvn --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=powsybl-ci-github
          -Dsonar.projectKey=com.powsybl:powsybl-study-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image
        if: github.ref == 'refs/heads/master'
        run: >
          mvn --batch-mode jib:build
          -Djib.httpTimeout=60000
          -Djib.to.image=docker.io/powsybl/study-server
          -Djib.to.auth.username=powsyblci
          -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }}

      - name: Broadcast update event
        if: github.ref == 'refs/heads/master'
        uses: geofjamg/broadcast-event@master
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: study_server_updated
