name: Patch

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: version to patch (vX.X)
        required: true

jobs:
  run-patch:
    uses: powsybl/github-ci/.github/workflows/patch-backend-app-generic.yml@8e990dd28cbccff180f322903ac1e3131ab3632a
    with:
      githubappId: ${{ vars.GRIDSUITE_ACTIONS_APPID }}
      dockerImage: docker.io/gridsuite/study-server
      dockerUsername: gridsuiteci
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
    secrets:
      githubappPrivateKey: ${{ secrets.GRIDSUITE_ACTIONS_SECRET }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}

