name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release version (vX.X)
        required: true
      gitReference:
        description: SHA of the commit from where to release or branch name
        required: true

jobs:
  run-release:
    uses: powsybl/github-ci/.github/workflows/release-backend-app-generic.yml@69b162754c0728d9aeb2ea568eaf47f28f60fafb
    with:
      githubappId: ${{ vars.GRIDSUITE_ACTIONS_APPID }}
      dockerImage: docker.io/gridsuite/study-server
      dockerUsername: gridsuiteci
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
      gitReference: ${{ github.event.inputs.gitReference }}
    secrets:
      VERSIONBUMP_GHAPP_PRIVATE_KEY: ${{ secrets.VERSIONBUMP_GHAPP_PRIVATE_KEY }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
